### ISSUE TITLE
Can’t see people in livemessage messages don’t save/archive

### ISSUE THREAD

**Issue by TheSpireXD** [rebane2001/livemessage#34]
Really annoying glitch. Some people just don’t show up also I can’t see old message history

**Comment by gdcfxvnjvbncvb** [comment]
I've got the same problem.
When someone sends me a message, I can see him in "chat" section of livemessage, and reply.
But as soon as I relaunch minecraft, that same person doesn't show up in "chat" section, and I can't see the message history.
Also, if that person comes back online and sends me an another message, he still doesn't appear in the "chat" section, and he doesn't appear if I search for him.

I use these mods:
Forge 14.23.5.2860 1.12.2
Impact-4.9.1-1.12.2
journeymap-1.12.2-5.7.1
LunatriusCore-1.12.2-1.2.0.42-universal
Schematica-1.12.2-1.8.4-universal

@TheSpireXD What client and mods are you using ?

**Comment by rebane2001** [comment]
You probably have a corrupted json file for that person, you can check in the game folders

**Comment by gdcfxvnjvbncvb** [comment]
If I delete "\.minecraft\config\livemessage\messages" the people appear again in livemessage.
But as soon as I send or receive a message, then restart the game, that person disappears again.

For example, I send a message to LolRiTTeRBot, he appears in the "chat" section.
I close and relaunch the game, and LolRiTTeRBot doesn't appear in "chat" section. And if I search for him, he doesn't appear anymore.

I just tried the following:
*Uninstall Minecraft
*Delete \.minecraft\
*Reinstall Minecraft
*Reinstall Forge 14.23.5.2860 1.12.2
*Put livemessage-1.1.2-standard.jar in \mods\ folder
But the problem is still the same :(

The files in \messages\ save as .jsonl files.
I can open them with notepad.

**Comment by rebane2001** [comment]
Have you also tried removing the settings json for the affected users?

**Comment by gdcfxvnjvbncvb** [comment]
If you are talking about \.minecraft\config\livemessage.cfg
Yes, i tried deleting it.

**Comment by rebane2001** [comment]
No I mean the profiles in \settings\

**Comment by gdcfxvnjvbncvb** [comment]
.minecraft\config\livemessage\settings is empty

**Comment by rebane2001** [comment]
When you send a message to LolRiTTeRBot for example, are there any errors in the game log? Same for when you open a profile up?

**Comment by gdcfxvnjvbncvb** [comment]
I'm not really familiar with these logs.
I searched for LolRiTTeRBot, and his UUID b30d9800-f9b7-4de8-a276-f40b3d706042.


> [19:53:22] [Client thread/INFO] [STDOUT]: [net.minecraft.client.gui.GuiNewChat:handler$printChatMessageWithOptionalDeletion$zfe000:541]: [Livemessage] Message sent to LolRiTTeRBot > test
[19:53:22] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] to LolRiTTeRBot: test`

> [19:54:15] [pool-3-thread-1/INFO] [STDOUT]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:57]: [Livemessage] Looking up: b30d9800-f9b7-4de8-a276-f40b3d706042
[19:54:15] [Client thread/INFO] [journeymap]: JourneyMap log initialized.
[19:54:15] [Client thread/INFO] [journeymap]: initialize ENTER
[19:54:15] [Client thread/INFO] [journeymap]: [ClientAPI] built with JourneyMap API 1.4
[19:54:15] [Client thread/INFO] [journeymap]: Initializing plugins with Client API: journeymap.client.api.impl.ClientAPI
[19:54:15] [Client thread/INFO] [journeymap]: initialize EXIT, elapsed count 0 avg ?ms
[19:54:15] [Client thread/INFO] [FML]: Injecting itemstacks
[19:54:15] [Client thread/INFO] [FML]: Itemstack injection complete
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: java.io.FileNotFoundException: https://api.mojang.com/user/profiles/b30d9800-f9b7-4de8-a276-f40b3d706042/names
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LivemessageUtil.getResources(LivemessageUtil.java:131)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LivemessageUtil.getResources(LivemessageUtil.java:110)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LiveProfileCache.pollPastNames(LiveProfileCache.java:62)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LiveProfileCache.getLiveprofileFromUUID(LiveProfileCache.java:186)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LiveProfileCache.lambda$preloadProfiles$0(LiveProfileCache.java:116)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at com.rebane2001.livemessage.util.LiveProfileCache$$Lambda$159/1545614526.call(Unknown Source)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:54:15] [pool-3-thread-1/INFO] [STDERR]: [com.rebane2001.livemessage.util.LiveProfileCache:pollPastNames:82]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by rebane2001** [comment]
Gotcha, thanks, I'll see if I can get a fix out

**Comment by gdcfxvnjvbncvb** [comment]
Thanks, it's good this can help you out ^^
As I can understand, with my limited knowledge, is that an api call fails.
